version: "3.8"
services:
    db:
        image: postgres
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data
        
    pizza:
        volumes:
            - ./pizza:/app:cached
        build: ./pizza
        ports:
            - 8080:8080
        depends_on:
            - "db"
        env_file:
            - .env
        command: "air main.go"
